# Generated by Django 3.2.9 on 2022-04-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50, verbose_name='Car name')),
                ('car_model', models.CharField(blank=True, max_length=50, verbose_name='Car model')),
            ],
            options={
                'verbose_name': 'Car category',
                'verbose_name_plural': 'car category',
            },
        ),
        migrations.CreateModel(
            name='CoverCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cover category',
                'verbose_name_plural': 'cover category',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.BooleanField(default=False, verbose_name='Cover patterns')),
                ('color', models.CharField(max_length=10, verbose_name='Cover color')),
                ('price', models.IntegerField(verbose_name='Cover price')),
                ('image', models.ImageField(null=True, upload_to='product/%Y/%m/%d', verbose_name='Picture')),
                ('phone_number', models.CharField(max_length=20)),
                ('instagram', models.CharField(max_length=30, verbose_name='Instagram link')),
                ('telegram', models.CharField(blank=True, max_length=30, verbose_name='Telegram link')),
                ('car_name', models.ManyToManyField(to='product.CarsCategory')),
                ('cover', models.ManyToManyField(to='product.CoverCategory')),
            ],
            options={
                'verbose_name': 'Covers',
                'verbose_name_plural': 'covers',
            },
        ),
    ]
