# Generated by Django 3.2.9 on 2022-04-27 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category_news', models.CharField(choices=[('SALES', 'SALES'), ('NEW PRODUCTS', 'NEW PRODUCTS')], max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('created_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'news',
            },
        ),
    ]
